/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IconLogosElement: typeof import('~icons/logos/element')['default']
    IconLogosEmacsClassic: typeof import('~icons/logos/emacs-classic')['default']
    IconLogosLodash: typeof import('~icons/logos/lodash')['default']
    IconLogosTypescriptIcon: typeof import('~icons/logos/typescript-icon')['default']
    IconLogosVitejs: typeof import('~icons/logos/vitejs')['default']
    IconLogosVue: typeof import('~icons/logos/vue')['default']
    IconLogosVueuse: typeof import('~icons/logos/vueuse')['default']
    IconSimpleIconsIconify: typeof import('~icons/simple-icons/iconify')['default']
    IconSvgPinia: typeof import('~icons/svg/pinia')['default']
    IconVscodeIconsFolderTypePlugin: typeof import('~icons/vscode-icons/folder-type-plugin')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
